spring.application.name=customers-api

spring.datasource.url=jdbc:h2:mem:customersdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


app.password.regex=^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).{8,}$
app.password.message=La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un número
