spring.application.name=customers-api

spring.datasource.url=jdbc:h2:mem:customersdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


app.password.regex=^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).{8,}$
app.password.message=La contrase�a debe tener al menos 8 caracteres, una may�scula, una min�scula y un n�mero

app.email.regex=^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$
app.email.message=El formato del correo no es valido



app.jwt.secret=mi-clave-secreta-muy-larga-para-hs256-al-menos-32-bytes
app.jwt.expiration-ms=86400000
